paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: src/content/blog
    icon: event_available
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  legal:
    path: src/content/legal
    icon: eda
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_blog:
    path: src/pages/blog
    icon: call_log
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_components:
    path: src/pages/components
    icon: settop_component
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_contact:
    path: src/pages/contact
    icon: page_control
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_legal:
    path: src/pages/legal
    icon: pageless
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_privacy_policy:
    path: src/pages/privacy-policy
    icon: privacy_tip
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_team:
    path: src/pages/team
    icon: page_header
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_theme_info:
    path: src/pages/theme-info
    icon: page_info
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  team:
    path: src/content/team
    icon: tram
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Asia/Tokyo
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
